on:
  workflow_dispatch:
  
  schedule:
    - cron: "*/30 * * * *"

name: Build, test, and deploy

env:
  NAPI_CLI_VERSION: 2.7.0
  TURBO_VERSION: 1.3.2-canary.1
  RUST_TOOLCHAIN: nightly-2022-02-23
  PNPM_VERSION: 7.2.1

jobs:
  test-native:
    name: Unit Test Native Code
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - run: echo ::set-output name=SWC_CHANGE::$(node scripts/run-for-change.js --type next-swc --exec echo 'yup')
        id: swc-change

      - run: echo ${{ steps.swc-change.outputs.SWC_CHANGE }}

      - name: Install
        if: ${{ steps.swc-change.outputs.SWC_CHANGE == 'yup' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          profile: minimal

      - run: cd packages/next-swc && cargo test
        if: ${{ steps.swc-change.outputs.SWC_CHANGE == 'yup' }}

  test-wasm:
    name: Test the wasm build
    runs-on: ubuntu-18.04
    needs: [build, build-native-test, build-wasm-dev]

    steps:
      - uses: actions/cache@v3
        if: ${{needs.build.outputs.docsChange == 'nope'}}
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - uses: actions/download-artifact@v3
        if: ${{needs.build.outputs.docsChange == 'nope'}}
        with:
          name: wasm-dev-binary
          path: packages/next-swc/crates/wasm/pkg-nodejs

      - run: ls packages/next-swc/crates/wasm
        if: ${{needs.build.outputs.docsChange == 'nope'}}

      - uses: actions/download-artifact@v3
        if: ${{needs.build.outputs.docsChange == 'nope'}}
        with:
          name: next-swc-test-binary
          path: packages/next-swc/native

      # node version needs to be 16+ to use --no-addons option
      - name: Setup node
        if: ${{needs.build.outputs.docsChange == 'nope'}}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - run: npm i -g playwright-chromium@1.22.2 && npx playwright install-deps
        if: ${{needs.build.outputs.docsChange == 'nope'}}

      - run: node ./scripts/setup-wasm.mjs
        if: ${{needs.build.outputs.docsChange == 'nope'}}

      - run: npm i -g pnpm@${PNPM_VERSION}
        if: ${{needs.build.outputs.docsChange == 'nope'}}

      - run: TEST_WASM=true xvfb-run node run-tests.js test/integration/production/test/index.test.js
        if: ${{needs.build.outputs.docsChange == 'nope'}}

      - run: TEST_WASM=true xvfb-run node run-tests.js test/production/react-18-streaming-ssr/index.test.ts
        if: ${{needs.build.outputs.docsChange == 'nope'}}
